Update postinst

diff --git a/homeassistant-supervised/DEBIAN/postinst b/homeassistant-supervised/DEBIAN/postinst
--- a/homeassistant-supervised/DEBIAN/postinst
+++ b/homeassistant-supervised/DEBIAN/postinst
@@ -177,8 +177,15 @@ then
         sed -i.bak 's/$/ systemd.unified_cgroup_hierarchy=false/' /boot/firmware/cmdline.txt
         touch /var/run/reboot-required
     fi
+elif [ -f /boot/uEnv.txt ]
+then
+    if ! grep -q "systemd.unified_cgroup_hierarchy=false" /boot/uEnv.txt; then
+        info "Switching to cgroup v1"
+        sed -i.bak 's/$/ systemd.unified_cgroup_hierarchy=0/' /boot/uEnv.txt
+        touch /var/run/reboot-required
+    fi
 else
-    warn "Could not find /etc/default/grub or /boot/firmware/cmdline.txt failed to switch to cgroup v1"
+    warn "Could not find /etc/default/grub or /boot/firmware/cmdline.txt or /boot/uEnv.txt failed to switch to cgroup v1"
 fi
 info "Within a few minutes you will be able to reach Home Assistant at:"
 info "http://homeassistant.local:8123 or using the IP address of your"
